In [141]:
import torch
torch.__version__

'2.0.1+cu117'

In [142]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [143]:
scaler.ndim

0

In [144]:
vector = torch.tensor([2,3,4,5])
vector

tensor([2, 3, 4, 5])

In [145]:
vector.ndim

1

In [146]:
vector.shape

torch.Size([4])

In [147]:
matrix = torch.tensor([[[1,2],[4,5],[7,8]]])
matrix

tensor([[[1, 2],
         [4, 5],
         [7, 8]]])

In [148]:
matrix.ndim

3

In [149]:
matrix.shape

torch.Size([1, 3, 2])

In [150]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.2666, 0.6274, 0.2696, 0.4414],
         [0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062]]),
 torch.float32)

In [151]:
random_img_size_tensor = torch.rand(size=(244,244,3))
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [152]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [153]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [154]:
# zero_to_one_ = torch.range(0,10)
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [155]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [156]:
ten_ones = torch.ones_like(input=zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [157]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [158]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [159]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.4955, 0.1359, 0.5243, 0.5060],
        [0.9585, 0.6795, 0.3179, 0.4151],
        [0.6428, 0.2465, 0.1096, 0.7105]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [160]:
add = torch.tensor([1,2,3])
add + 10

tensor([11, 12, 13])

In [161]:
sub = torch.tensor([2,2,2])
sub

tensor([2, 2, 2])

In [162]:
add = add - 10
add

tensor([-9, -8, -7])

In [163]:
add = add + 11
add

tensor([2, 3, 4])

In [164]:
torch.multiply(add, 2)

tensor([4, 6, 8])

In [165]:
add

tensor([2, 3, 4])

In [166]:
print(add,'*',add)
print(add * sub)

tensor([2, 3, 4]) * tensor([2, 3, 4])
tensor([4, 6, 8])


In [167]:
m1 = torch.tensor([1,2,3])
torch.matmul(m1, m1)

tensor(14)

In [168]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(m1)):
  value += m1[i] * m1[i]
value

CPU times: total: 0 ns
Wall time: 991 μs


tensor(14)

In [169]:
a = torch.tensor([[1,2],
                 [2,3],
                 [3,4]],dtype=torch.float32)
b = torch.tensor([[1,2],
                 [2,3],
                 [3,4]],dtype=torch.float32)
a.shape
b.shape
# torch.matmul(a, b)

torch.Size([3, 2])

In [170]:
print(a)
print(b.T)

tensor([[1., 2.],
        [2., 3.],
        [3., 4.]])
tensor([[1., 2., 3.],
        [2., 3., 4.]])


In [171]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {a.shape}, tensor_B = {b.shape}\n")
print(f"New shapes: tensor_A = {a.shape} (same as above), tensor_B.T = {b.T.shape}\n")
print(f"Multiplying: {a.shape} * {b.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(a, b.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 5.,  8., 11.],
        [ 8., 13., 18.],
        [11., 18., 25.]])

Output shape: torch.Size([3, 3])


In [172]:
# torch.mm is a shortcut for matmul
torch.mm(a, b.T)

tensor([[ 5.,  8., 11.],
        [ 8., 13., 18.],
        [11., 18., 25.]])

In [173]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = a
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [3.3644, 1.7131, 0.4592, 0.4575, 0.2355, 1.7308],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [174]:
m = torch.arange(0,100,10)
m

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [175]:
print(f"Minimum: {m.min()}")
print(f"Maximum: {m.max()}")
print(f"Mean: {m.type(torch.float32).mean()}")
print(f"Sum: {m.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [176]:
tensor = torch.arange(0, 100, 10)
print(tensor)

print(f"Minimum: {tensor.argmin()}")
print(f"Maximum: {tensor.argmax()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 9


In [177]:
tensor.dtype

torch.int64

In [178]:
tensor_dtype = tensor.type(torch.float64)
tensor_dtype

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float64)

In [179]:
tensor.dtype

torch.int64

In [180]:
z = torch.arange(1, 10)
z, z.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [181]:
z_reshaped = z.reshape(1,9)
z_reshaped, z_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [182]:
x= z.view(1,9)
x

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [183]:
x[:, 0] =5
x, z

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [184]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked


tensor([[[5, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[5, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[5, 2, 3, 4, 5, 6, 7, 8, 9]],

        [[5, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [185]:
print(f"previous tensor: {z_reshaped}")
print(f"previous shape: {z_reshaped.shape}")

z_squeezed = z_reshaped.squeeze()
print(f"new tensor: {z_squeezed}")
print(f"new tensor shape: {z_squeezed.shape}")

previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
previous shape: torch.Size([1, 9])
new tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
new tensor shape: torch.Size([9])


In [186]:
z_stacked = torch.stack([z_squeezed,z_squeezed,z_squeezed,z_squeezed], dim=0)
z_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [187]:
print(f"previous tensor: {z_squeezed}")
z_unsqueeze = z_squeezed.unsqueeze(dim=0)
print(f"new tensor: {z_unsqueeze}")

previous tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
new tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])


In [188]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [189]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [190]:
x[:, 0]

tensor([[1, 2, 3]])

In [191]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [192]:
x[:, 1, 1]

tensor([5])

In [193]:
x[0, 0, :]

tensor([1, 2, 3])

In [194]:
import numpy as np
array = np.arange(1,8)
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3, 4, 5, 6, 7]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))

In [195]:
array = array + 1
array, tensor

(array([2, 3, 4, 5, 6, 7, 8]),
 tensor([1, 2, 3, 4, 5, 6, 7], dtype=torch.int32))

In [196]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [197]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [198]:
tensor_a = torch.rand(3,4)
tensor_b = torch.rand(3,4)

print(f"tensor_a: {tensor_a}")
print(f"tensor_b: {tensor_b}")
print(f"does tensro_a is equal to tensor_b (anywhere)")
tensor_a == tensor_b

tensor_a: tensor([[0.2666, 0.6274, 0.2696, 0.4414],
        [0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062]])
tensor_b: tensor([[0.9516, 0.0753, 0.8860, 0.5832],
        [0.3376, 0.8090, 0.5779, 0.9040],
        [0.5547, 0.3423, 0.6343, 0.3644]])
does tensro_a is equal to tensor_b (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [199]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [200]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [201]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [202]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [203]:
sev = torch.rand(7,7)
sev

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
        [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
        [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
        [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]])

In [204]:
mat1 = torch.rand(1,7)
mat2 = torch.rand(1,7)
mat1, mat2

(tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036]]),
 tensor([[0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041]]))

In [205]:
mat2_t = torch.tensor(mat2.T)
mat2_t, mat2_t.shape

C:\Users\nikhil\AppData\Local\Temp\ipykernel_732\4118708267.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mat2_t = torch.tensor(mat2.T)


(tensor([[0.2018],
         [0.2018],
         [0.9497],
         [0.6666],
         [0.9811],
         [0.0874],
         [0.0041]]),
 torch.Size([7, 1]))

In [206]:
mat_mul = torch.mm(mat1, mat2_t)
mat_mul

tensor([[1.3799]])